import type { Metadata } from "next";
import { Archivo_Black, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

// Peso estático en vez de la variable: el eje wght costaría el doble de bytes
// y aquí nadie interpola peso, porque solo se animan transform y opacity.
// El subset latin ya trae ñ, tildes, ¿ y ¡: latin-ext sobra y pesa.
const cuerpo = IBM_Plex_Mono({
  variable: "--fuente-cuerpo",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const titular = Archivo_Black({
  variable: "--fuente-titular",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${cuerpo.variable} ${titular.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
